FROM  centos:latest

RUN  yum install sudo -y
RUN  yum install  wget -y
RUN  yum install java -y
RUN  sudo yum install python36 -y
RUN  sudo yum install  git  -y
RUN  sudo yum install  vim -y
RUN  sudo yum install ncurses -y
RUN  sudo yum install net-tools -y
RUN  yum install openssh-clients openssh-server -y
RUN  curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
RUN  chmod +x kubectl
RUN  mv kubectl  /usr/bin/
RUN  mkdir  /kube_cert/
COPY c*  /kube_cert/
COPY  config /root/.kube/config
COPY ssh/  /etc/ssh/
RUN  echo root:hatred | chpasswd
RUN  mkdir /workspace/

CMD /usr/sbin/sshd -D && /bin/bash


